# 应用服务 WEB 访问端口
server:
  port: 8085
# 自定义常量
constants:
  posterUrlPostNormal: "http://49.235.113.96:8086/poster/from_tcmd"
  posterUrlPostReject: "http://49.235.113.96:8086/poster/from_tcmd/reject"
  aesKey: "0123456789012345"
  logLocation: "tail -f /usr/local/bttomcat/tomcat8/webapps/TCManager/TCMD/spring.log"
  presInfoLocation: "/usr/local/bttomcat/tomcat8/webapps/TCManager/TCMD/PresInfo.xlsx"
  shipInfoLocation: "/usr/local/bttomcat/tomcat8/webapps/TCManager/TCMD/ShipInfo.xlsx"
  presHisLocation: "/usr/local/bttomcat/tomcat8/webapps/TCManager/TCMD/PresHis.xlsx"
  shipHisLocation: "/usr/local/bttomcat/tomcat8/webapps/TCManager/TCMD/ShipHis.xlsx"
#  presInfoLocation: "C:/Users/Lenovo/Desktop/PresInfo.xlsx"
#  shipInfoLocation: "C:/Users/Lenovo/Desktop/ShipInfo.xlsx"
#  presHisLocation: "C:/Users/Lenovo/Desktop/PresHis.xlsx"
#  shipHisLocation: "C:/Users/Lenovo/Desktop/ShipHis.xlsx"
# 应用名称
spring:
  application:
    name: tcmd
  # 数据源
  datasource:
    # 数据库驱动：
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源名称，地址，账号，密码
    name: defaultDataSource
    url: jdbc:mysql://8.134.147.174:3306/tcmd?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false
    username: root
    password: e01jnor36dq5
    # 连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
  # rabbitmq
  rabbitmq:
    host: 8.134.147.174
    port: 5672
  # java mail
  mail:
    host: smtp.qq.com
    protocol: smtps
    username: 2479711422@qq.com
    password: hyfaxtomhlniebdi
    port: 465
    properties:
      mail:
        smtp:
          socketFactort:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  # redis相关
  redis:
    host: 8.134.147.174
    port: 6379
    password: root
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
# 下面这些内容是为了让MyBatis映射
# 指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mappers/*xml
  # 指定Mybatis的实体目录
  type-aliases-package: cn.calendo.tcmdistribution.entity
# mybatis-plus配置
mybatis-plus:
  # 别名扫描包
  type-aliases-package: cn.calendo.tcmdistribution.entity
  configuration:
    # 在映射实体或属性时，将数据表名与字段名的下划线去掉，按照驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
# 输出日志等级
logging:
  group:
    ebank: cn.calendo.tcmdistribution.controller,cn.calendo.tcmdistribution.service,cn.calendo.tcmdistribution.dao
  level:
    root: info
    ebank: info
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
    rolling-file-name: TCMD_Server.%d{yyyy-MM-dd}.%i.log
  file:
    path: /usr/local/bttomcat/tomcat8/webapps/TCManager/TCMD
    max-size: 20MB